### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by yss14** [leftshift/python_mvg_departures#1]
Hey

Nice work man! Where do I get the API key? Do I have to use your key?

**Comment by leftshift** [comment]
Well, It's not really my key, either… ^^
I'm using the one their web frontend uses. That's kind of ugly, I know, but
there seems to be no official way to get your own api key…

So yes, for now, just use the one in the code. I might contact mvg one day
and kindly ask them if they have any plans to give out keys

Cheers, Adrian

yss14 <notifications@github.com> schrieb am Do., 10. Nov. 2016, 08:41:

**Comment by yss14** [comment]
Thanks for the quick response and information!

**Comment by leftshift** [comment]
No problem ;)
I think I'll add a note about it in the docs

yss14 <notifications@github.com> schrieb am Do., 10. Nov. 2016, 09:59:
